[workspace]

members = [
  "day_1",
  "day_2",
  "day_3",
  "day_4",
  "day_5",
  "day_6",
  "day_7",
  "day_9",
  "day_10",
  "day_11",
  "day_12",
  "day_13",
  "day_14",
  "day_15",
  "day_17",
  "day_20",
  "day_21",
  "day_22"
]
